### ISSUE TITLE
add support for bypassing invalid ssl certs

### ISSUE THREAD

**Issue by ByronAP** [coinigy/PureWebSockets#1]
library needs an option to ignore invalid/expired certs

**Comment by ByronAP** [comment]
https://github.com/dotnet/corefx/issues/12038

**Comment by LadislavBohm** [comment]
I believe that this issue is preventing me from deploying my application to Azure App Service. As I can see, SSL cert authentication bypass is still not implemented in .NET Core.

The websocket connection works fine when running from local Windows 10 OS, but fails when deployed to Azure App Service which runs on Windows Server 2012 (they should be upgrading to 2016 in the near future). Is the certificate used for socket connections valid or is there some other workaround for this issue?

Exception in .NET Core is not very specific, however this is a stack trace.
```
(Unable to connect to the remote server) ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.Http.WinHttpException: A security error occurred
[12/06/2017 08:54:23 > c3e1ee: INFO]    --- End of inner exception stack trace ---
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Net.WebSockets.WinHttpWebSocket.<ConnectAsync>d__18.MoveNext()
[12/06/2017 08:54:23 > c3e1ee: INFO] --- End of stack trace from previous location where exception was thrown ---
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
[12/06/2017 08:54:23 > c3e1ee: INFO]    at System.Net.WebSockets.WebSocketHandle.<ConnectAsyncCore>d__20.MoveNext()
[12/06/2017 08:54:23 > c3e1ee: INFO]    --- End of inner exception stack trace ---
```

**Comment by ByronAP** [comment]
this should be ready soon with the release of netstandard 2.1

**Comment by ByronAP** [comment]
https://github.com/dotnet/corefx/pull/28141
