### ISSUE TITLE
OnOpened Event didn't fire after reconnect

### ISSUE THREAD

**Issue by thetpaingwynn** [coinigy/PureWebSockets#15]
I'm not getting OnOpened Event after websocket close and reconnected. But websocket was reconnected successfully. Here is the error.
```
System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at PureWebSockets.PureWebSocket.<StartSender>b__59_0()
```

**Comment by ByronAP** [comment]
This is by design (reconnecting without firing an event). We could make this an optional behavior. Could you give a bit more information about the error and how it relates to auto reconnect?

**Comment by thetpaingwynn** [comment]
Hi @ByronAP,
Sorry for late reply. If it is by design then let it be. But It will be nice if we have option to fire event upon successful re-connection. Because some websocket require to send subscribe message upon reconnect. 

Here is the information about the error and my setup.

I initialize the `websocket` with `ReconnectStrategy` like this
```csharp
_webSocket = new PureWebSocket(_url, new PureWebSocketOptions
{
    DebugMode = true,
    SendDelay = 100,
    IgnoreCertErrors = true,
    MyReconnectStrategy = new ReconnectStrategy(1000)
});
```
At some point `OnError` event fired with this exception
```csharp
System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at PureWebSockets.PureWebSocket.<StartSender>b__59_0()
```
`OnStateChanged` event fired with State: `Aborted`,
then `OnStateChanged` event fired again with State: `Connecting`
After that I got welcome message from Websocket which is send upon every successful connection.
