### ISSUE TITLE
Whenever you call the Dispose method, it raises a socket error event

### ISSUE THREAD

**Issue by robborden** [coinigy/PureWebSockets#3]
When you call _ws.Dispose() it raises the following error in OnError handlers: 
```Method: ScSocket.ScSocket_OnError Error: The operation was canceled.  ```
I would guess this is somehow related to the cancellation token being cancelled.

**Comment by robborden** [comment]
{System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at PureWebSockets.PureWebSocket.<<StartSender>b__60_0>d.MoveNext()}

**Comment by ByronAP** [comment]
yes this is expected behavior.
